services:
  backend:
    build: ./moodly-social-api
    container_name: moodly-backend
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

  gateway:
    build: ./moodly-social-web
    container_name: moodly-gateway
    ports:
      - "8081:8081"
    depends_on:
      - backend
