spring.application.name=moodly-social-api
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
logging.level.com.example.moodly_social_api=DEBUG
logging.file.path=${LOGGING_FILE_PATH:logs}
server.port=${SERVER_PORT:8080}

debug=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
